# Generated by Django 2.2.3 on 2020-07-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(default='item.ipg', upload_to='item_pictures'),
        ),
    ]
